/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserStats = IDL.Record({
  'bestCompletionTimeMs' : IDL.Nat,
  'totalDeaths' : IDL.Nat,
  'totalWins' : IDL.Nat,
  'bestStage' : IDL.Nat,
});
export const CustomLevel = IDL.Record({
  'id' : IDL.Nat,
  'worldWidth' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorSession' : IDL.Text,
  'author' : IDL.Principal,
  'platformsJson' : IDL.Text,
  'bgHue' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminResetUsernames' : IDL.Func([IDL.Text], [], []),
  'claimOwnerPrincipal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLevel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteMyLevel' : IDL.Func([IDL.Text], [], []),
  'getAllUsernames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
      ['query'],
    ),
  'getLeaderboardWithUsernames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats, IDL.Text))],
      ['query'],
    ),
  'getLevelById' : IDL.Func([IDL.Nat], [IDL.Opt(CustomLevel)], ['query']),
  'getMyLevel' : IDL.Func([IDL.Text], [IDL.Opt(CustomLevel)], ['query']),
  'getMyLevels' : IDL.Func([IDL.Text], [IDL.Vec(CustomLevel)], ['query']),
  'getMyStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
  'getMyUsername' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getPublicLevels' : IDL.Func([], [IDL.Vec(CustomLevel)], ['query']),
  'getSpeedLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
      ['query'],
    ),
  'getSpeedLeaderboardWithUsernames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats, IDL.Text))],
      ['query'],
    ),
  'registerUsername' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetMyUsername' : IDL.Func([IDL.Text], [], []),
  'saveCustomLevel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'saveGameResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserStats = IDL.Record({
    'bestCompletionTimeMs' : IDL.Nat,
    'totalDeaths' : IDL.Nat,
    'totalWins' : IDL.Nat,
    'bestStage' : IDL.Nat,
  });
  const CustomLevel = IDL.Record({
    'id' : IDL.Nat,
    'worldWidth' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorSession' : IDL.Text,
    'author' : IDL.Principal,
    'platformsJson' : IDL.Text,
    'bgHue' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminResetUsernames' : IDL.Func([IDL.Text], [], []),
    'claimOwnerPrincipal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLevel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteMyLevel' : IDL.Func([IDL.Text], [], []),
    'getAllUsernames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
        ['query'],
      ),
    'getLeaderboardWithUsernames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats, IDL.Text))],
        ['query'],
      ),
    'getLevelById' : IDL.Func([IDL.Nat], [IDL.Opt(CustomLevel)], ['query']),
    'getMyLevel' : IDL.Func([IDL.Text], [IDL.Opt(CustomLevel)], ['query']),
    'getMyLevels' : IDL.Func([IDL.Text], [IDL.Vec(CustomLevel)], ['query']),
    'getMyStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
    'getMyUsername' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getPublicLevels' : IDL.Func([], [IDL.Vec(CustomLevel)], ['query']),
    'getSpeedLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
        ['query'],
      ),
    'getSpeedLeaderboardWithUsernames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats, IDL.Text))],
        ['query'],
      ),
    'registerUsername' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetMyUsername' : IDL.Func([IDL.Text], [], []),
    'saveCustomLevel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'saveGameResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };